/* Network definitions */
resource "google_compute_network" "neverland-gcn" {
  name                    = "neverland-gcn"
  auto_create_subnetworks = false
}

resource "google_compute_subnetwork" "neverland-gcn-subnetwork" {
  name          = "neverland-gcn-subnetwork"
  ip_cidr_range = var.vpc_cidr
  region        = "europe-west6"
  network       = google_compute_network.neverland-gcn.id
}

/* Ansible variables */
resource "local_file" "tf_network_vars_file_new" {
  content  = <<-DOC
    # Ansible vars_file containing variable values from Terraform.
    # Generated by Terraform mgmt configuration.
    vpc_cidr: ${var.vpc_cidr}
    DOC
  filename = "../ansible/terraform_variables/tf_network_vars_file.yml"
}


/* Firewall defitions */
resource "google_compute_firewall" "allow-ssh" {
  name    = "allow-ssh"
  network = google_compute_network.neverland-gcn.id

  allow {
    protocol = "tcp"
    ports    = ["22"]
  }

  target_tags   = ["bastion", "ioi"]
  source_ranges = ["0.0.0.0/0"]
}

resource "google_compute_firewall" "internal-ssh" {
  name    = "internal-ssh"
  network = google_compute_network.neverland-gcn.id

  allow {
    protocol = "tcp"
    ports    = ["22"]
  }

  target_tags = ["internal"]
  source_tags = ["bastion"]
}

resource "google_compute_firewall" "allow-all-internal" {
  name    = "allow-all-internal"
  network = google_compute_network.neverland-gcn.id

  allow {
    protocol = "all"
  }

  target_tags = ["internal"]
  source_tags = ["internal"]
}

resource "google_compute_firewall" "allow-proxy" {
  name    = "allow-proxy"
  network = google_compute_network.neverland-gcn.id

  allow {
    protocol = "tcp"
    ports    = ["1234"]
  }

  target_tags   = ["proxy"]
  source_ranges = ["0.0.0.0/0"]
}

