apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: kialivirtualservice
spec:
  hosts:
  - neverland.com
  gateways:
  - neverlandgateway
  http:
  - match:
    - uri:
        prefix: /kiali
    name: KialiDashboard
    route:
    - destination:
        port:
          number: 20001
        host: kiali.istio-system.svc.cluster.local
