- name: Cluster Settings
  hosts: portOfNeverland
  vars_files:
  - ./terraform_variables/tf_island-of-intelligence_vars_file.yml
  - ./terraform_variables/tf_network_vars_file.yml
  - ./terraform_variables/tf_k8node_vars_file.yml

  tasks:
  - name: Wait 300 seconds for ssh timeout, but only start checking after 1 seconds
    wait_for_connection:
      delay: 1
      timeout: 300

  - name: taint monitortown
    become_user: fisherman
    command: kubectl taint node monitortown purpose=monitoring:NoSchedule

  - name: install Pod network
    become: yes
    become_user: fisherman
    shell: kubectl apply -f https://projectcalico.docs.tigera.io/manifests/calico.yaml
    args:
      chdir: $HOME

  - name: create monitoring namespace
    become_user: fisherman
    command: kubectl create namespace monitoring

  - name: helm repo add metrics-server
    become_user: fisherman
    command: helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/

  - name: helm repo update
    become_user: fisherman
    command: helm repo update

  - name: Copy metrics-server_values.yaml
    copy:
     src: metrics-server_values.yaml
     dest: /tmp
     mode: 0755

  - name: install metrics-server via helm
    become_user: fisherman
    command: helm install --namespace monitoring metrics-server metrics-server/metrics-server -f /tmp/metrics-server_values.yaml

  - name: Delete metrics-server_values.yaml
    file:
     path: /tmp/metrics-server_values.yaml
     state: absent

  - name: metrics-server install
    become_user: fisherman
    command: kubectl apply -f https://github.com/kubernetes-sigs/metrics-server/releases/latest/download/components.yaml

  - name: approve pending certificate
    become_user: fisherman
    shell:
      cmd: kubectl get csr | grep Pending | awk '{print $1}' | xargs kubectl certificate approve

