- name: Cluster Settings
  hosts: portOfNeverland
  become_user: fisherman
  vars_files:
  - ./terraform_variables/tf_island-of-intelligence_vars_file.yml
  - ./terraform_variables/tf_network_vars_file.yml
  - ./terraform_variables/tf_k8node_vars_file.yml

  tasks:
  - name: Wait 300 seconds for ssh timeout, but only start checking after 1 seconds
    wait_for_connection:
      delay: 1
      timeout: 300

  - name: approve pending certificate
    shell:
      cmd: kubectl get csr | grep Pending | grep kubelet-serving | awk '{print $1}' | xargs kubectl certificate approve

  - name: taint infrastructure towns
    command: kubectl taint node {{item}} node-role.kubernetes.io/infra:NoSchedule
    loop: "{{infrastructure_nodes}}"

  - name: label infrastructure towns
    command: kubectl label node {{item}} node-role.kubernetes.io/infra="{{loop_index+1}}"
    loop: "{{infrastructure_nodes}}"
    loop_control:
      index_var: loop_index

  - name: label worker towns
    command: kubectl label node {{item}} node-role.kubernetes.io/worker="{{loop_index+1}}"
    loop: "{{worker_nodes}}"
    loop_control:
      index_var: loop_index

  - name: create monitoring namespace
    command: kubectl create namespace monitoring

