- name: goldilocks uninstall
  hosts: portOfNeverland
  gather_facts: no
  become_user: fisherman
  vars_files:
  - ./terraform_variables/tf_island-of-intelligence_vars_file.yml
  - ./terraform_variables/tf_network_vars_file.yml
  - ./terraform_variables/tf_k8node_vars_file.yml

  tasks:
  - name: Wait 300 seconds for ssh timeout, but only start checking after 1 seconds
    wait_for_connection:
      delay: 1
      timeout: 300

  - name: Uninstall goldilocks via helm
    command: helm uninstall goldilocks --namespace goldilocks

  - name: Delete goldilocks namespace
    command: kubectl delete ns goldilocks --force 

  - name: Kill kubectl port-forward for goldilocks
    shell: ps -fe|grep "kubectl port-forward -n goldilocks service/goldilocks-dashboard --address=0.0.0.0 8080:80" | grep -v grep | awk '{print $2}' | xargs kill -s 9
    ignore_errors: yes

  - name: Check open ports 
    command: netstat -plnt
    register: result

  - name: Print open ports
    debug:
      msg: "{{ result.stdout_lines }}"
