- name: Goldilocks uninstall
  hosts: portOfNeverland
  gather_facts: false
  become: true
  become_user: fisherman
  vars_files:
  - ./terraform_variables/tf_island-of-intelligence_vars_file.yml
  - ./terraform_variables/tf_network_vars_file.yml
  - ./terraform_variables/tf_k8node_vars_file.yml

  tasks:
  - name: Wait 300 seconds for ssh timeout, but only start checking after 1 seconds
    ansible.builtin.wait_for_connection:
      delay: 1
      timeout: 300

  - name: Uninstall goldilocks via helm
    ansible.builtin.command: helm uninstall goldilocks --namespace goldilocks

  - name: Delete goldilocks namespace
    ansible.builtin.command: kubectl delete ns goldilocks --force

  - name: Unlabel target namespace
    ansible.builtin.command: kubectl label namespace {{ Namespace }}  goldilocks.fairwinds.com/enabled-

  - name: Kill kubectl port-forward for goldilocks
    ansible.builtin.shell: ps -fe|grep "kubectl port-forward -n goldilocks service/goldilocks-dashboard --address=0.0.0.0 8080:80" | grep -v grep | awk '{print $2}' | xargs kill -s 9
    ignore_errors: true

  - name: Check open ports
    ansible.builtin.command: netstat -plnt
    register: result

  - name: Print open ports
    ansible.builtin.debug:
      msg: "{{ result.stdout_lines }}"
