- name: Island of intelligence initialization  
  hosts: all
  gather_facts: no
  become: yes
  become_method: sudo
  become_user: root
  vars:
    username: spyman
    tinyproxy_port: "1234"
  vars_files:
  - ./terraform_variables/tf_ansible_island-of-intelligence_vars_file.yml
  - ./terraform_variables/tf_ansible_network_vars_file.yml
  tasks:
  - name: Wait 300 seconds for ssh timeout, but only start checking after 10 seconds
    wait_for_connection:
      delay: 10
      timeout: 300

  - name: update cache ~ apt-get update
    apt:
      update_cache: true

  - name: install tinyproxy
    apt:
      name:
      - tinyproxy
      state: present

  - name: Ensure the tinyproxy  port is {{ tinyproxy_port }}
    lineinfile:
      path: /etc/tinyproxy/tinyproxy.conf
      regexp: '^Port 8888'
      line: Port {{ tinyproxy_port }}

  - name: Ensure the tinyproxy  listens {{ ioi_internal_ip }}
    lineinfile:
      path: /etc/tinyproxy/tinyproxy.conf
      regexp: '^#Listen 192.168.0.1'
      line: Listen {{ ioi_internal_ip }}

  - name: Allow {{ vpc_cidr }} to access http proxy
    lineinfile:
      path: /etc/tinyproxy/tinyproxy.conf
      regexp: '^Allow 127.0.0.1'
      line: Allow {{ vpc_cidr }}

  - name: add iptable entry for tinyproxy
    iptables:
      chain: INPUT
      protocol: tcp
      destination_port: "{{ tinyproxy_port }}"
      source: "{{ vpc_cidr }}"
      jump: ACCEPT
      comment: tinyproxy

  - name: enable and restart tinyproxy
    service:
      name: tinyproxy
      state: restarted
      enabled: yes
  

