apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  components:
    pilot:
      k8s:
        nodeSelector:
          kubernetes.io/hostname: monitortown
        tolerations:
        - key: "purpose"
          operator: "Equal"
          value: "monitoring"
          effect: "NoSchedule"

