apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  profile: default
  components:
    pilot:
      k8s:
        nodeSelector:
          purpose: infratown
        tolerations:
        - key: "purpose"
          operator: "Equal"
          value: "infratown"
          effect: "NoSchedule"

