- name: Install metrics-server
  hosts: portOfNeverland
  gather_facts: false
  become: true
  become_user: fisherman
  vars_files:
  - ./terraform_variables/tf_island-of-intelligence_vars_file.yml
  - ./terraform_variables/tf_network_vars_file.yml
  - ./terraform_variables/tf_k8node_vars_file.yml

  tasks:
  - name: Wait 300 seconds for ssh timeout, but only start checking after 1 seconds
    ansible.builtin.wait_for_connection:
      delay: 1
      timeout: 300

  - name: helm repo add metrics-server
    ansible.builtin.command: helm repo add metrics-server https://kubernetes-sigs.github.io/metrics-server/

  - name: helm repo update
    ansible.builtin.command: helm repo update

  - name: Copy metrics-server_values.yaml
    ansible.builtin.template:
      src: metrics-server_values.yaml
      dest: /tmp
      mode: 0700

  - name: Install metrics-server via helm
    ansible.builtin.command: helm install --namespace monitoring metrics-server metrics-server/metrics-server -f /tmp/metrics-server_values.yaml

  - name: Delete temporary files on remote
    ansible.builtin.file:
      path: /tmp/metrics-server_values.yaml
      state: absent
