- name: Nevertown initialization  
  hosts: all
  gather_facts: no
  become: yes
  become_method: sudo
  become_user: root
 
  tasks:
  - name: Wait 300 seconds for ssh timeout, but only start checking after 60 seconds
    wait_for_connection:
      delay: 1
      timeout: 300

  - name: include CreateUbuntuUser role
    include_role:
      name: CreateUbuntuUser

  - name: install containerd and K8s with kubeadm
    include_role:
      name: InstallK8s
    vars:
      install_kubelet: true
      install_kubeadm: true
      install_kubectl: true
      K8s_version: 1.23.3-00


  - name: Execute command ‘date’
    command: "date"
    register: date_out
  - debug:
      var: date_out
