- name: Nevertown initialization
  hosts: Nevertowns[0]
  gather_facts: false
  become: true
  become_method: sudo
  become_user: root
  vars_files:
  - ./terraform_variables/tf_island-of-intelligence_vars_file.yml
  - ./terraform_variables/tf_network_vars_file.yml
  - ./variables.yaml

  tasks:
  - name: Wait 300 seconds for ssh timeout, but only start checking after 1 seconds
    ansible.builtin.wait_for_connection:
      delay: 1
      timeout: 300

  - name: Install containerd and K8s with kubeadm
    ansible.builtin.include_role:
      name: InstallK8s
    vars:
      install_kubelet: true
      install_kubeadm: true
      install_kubectl: false
      nodeType: "master-1"
      LBIP: "{{ kubeapi_LBfrontend_IP }}"
      KVVERSION: "v0.4.3"  
