prometheus:
  prometheusSpec:
    externalUrl: /prometheus/ 

alertmanager:
  alertmanagerSpec:
    replicas: 2
    nodeSelector:
      purpose: infratown
    tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "infratown"
      effect: "NoSchedule"
  podDisruptionBudget:
    enabled: true
    minAvailable: 1

grafana:
  adminPassword: admin
  nodeSelector:
    purpose: infratown
  tolerations:
  - key: "purpose"
    operator: "Equal"
    value: "infratown"
    effect: "NoSchedule"
kube-state-metrics:
 nodeSelector:
   purpose: infratown
 tolerations:
 - key: "purpose"
   operator: "Equal"
   value: "infratown"
   effect: "NoSchedule"
prometheus:
  prometheusSpec:
    replicas: 2
    nodeSelector:
      purpose: infratown
    tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "infratown"
      effect: "NoSchedule"
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
prometheusOperator:
  admissionWebhooks:
    nodeSelector:
      purpose: infratown
    tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "infratown"
      effect: "NoSchedule"
  nodeSelector:
    purpose: infratown
  tolerations:
  - key: "purpose"
    operator: "Equal"
    value: "infratown"
    effect: "NoSchedule"

