- name: Deploy prometheus and grafana stack
  become_user: fisherman
  become: true
  gather_facts: false
  hosts: portOfNeverland
  vars_files:
  - ./terraform_variables/tf_island-of-intelligence_vars_file.yml
  - ./terraform_variables/tf_network_vars_file.yml
  - ./terraform_variables/tf_k8node_vars_file.yml

  tasks:
  - name: Wait 300 seconds for ssh timeout, but only start checking after 1 seconds
    ansible.builtin.wait_for_connection:
      delay: 1
      timeout: 300

  - name: helm repo add prometheus-community
    ansible.builtin.command: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts

  - name: helm repo update
    ansible.builtin.command: helm repo update

  - name: Copy prometheus_values.yaml
    ansible.builtin.template:
      src: prometheus_values.yaml
      dest: /tmp
      mode: 0755

  - name: Install prometheus via helm
    ansible.builtin.command: helm install k8spromethuesstack --namespace monitoring prometheus-community/kube-prometheus-stack -f /tmp/prometheus_values.yaml

  - name: Delete temporary files on remote
    ansible.builtin.file:
      path: /tmp/prometheus_values.yaml
      state: absent

  - name: Patch grafana deployment
    ansible.builtin.shell:
      cmd: |
            kubectl -n monitoring patch deployments.apps k8spromethuesstack-grafana --patch-file=/dev/stdin <<-EOF
                            spec:
                              template:
                                spec:
                                  containers:
                                  - env:
                                    - name: GF_SERVER_ROOT_URL
                                      value: '%(protocol)s://%(domain)s:/grafana/'
                                    - name: GF_SERVER_DOMAIN
                                      value: neverland.com
                                    - name: GF_SERVER_SERVE_FROM_SUB_PATH
                                      value: "true"
                                    name: grafana
            EOF

  - name: Deploy grafana&prometheus virtual service
    ansible.builtin.shell:
      cmd: |
           cat <<EOF | kubectl apply -f -
                      apiVersion: networking.istio.io/v1alpha3
                      kind: VirtualService
                      metadata:
                        name: grafanaprometheusvirtualservice
                      spec:
                        hosts:
                        - neverland.com
                        gateways:
                        - neverlandgateway
                        http:
                        - match:
                          - uri:
                              prefix: /prometheus/
                          name: PrometheusDashboard
                          rewrite:
                            uri: /
                          route:
                          - destination:
                              host: k8spromethuesstack-kube-pr-prometheus.monitoring.svc.cluster.local
                              port:
                                number: 9090
                        - match:
                          - uri:
                              prefix: /grafana/
                          name: GrafanaDashboard
                          rewrite:
                            uri: /
                          route:
                          - destination:
                              host: k8spromethuesstack-grafana.monitoring.svc.cluster.local
                              port:
                                number: 80
                 EOF
