prometheus:
  prometheusSpec:
    externalUrl: /prometheus/ 

alertmanager:
  alertmanagerSpec:
    nodeSelector:
      kubernetes.io/hostname: monitortown
    tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "monitoring"
      effect: "NoSchedule"
grafana:
  adminPassword: admin
  nodeSelector:
    kubernetes.io/hostname: monitortown
  tolerations:
  - key: "purpose"
    operator: "Equal"
    value: "monitoring"
    effect: "NoSchedule"
kube-state-metrics:
 nodeSelector:
   kubernetes.io/hostname: monitortown
 tolerations:
 - key: "purpose"
   operator: "Equal"
   value: "monitoring"
   effect: "NoSchedule"
prometheus:
  prometheusSpec:
    nodeSelector:
      kubernetes.io/hostname: monitortown
    tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "monitoring"
      effect: "NoSchedule"
prometheusOperator:
  admissionWebhooks:
    nodeSelector:
      kubernetes.io/hostname: monitortown
    tolerations:
    - key: "purpose"
      operator: "Equal"
      value: "monitoring"
      effect: "NoSchedule"
  nodeSelector:
    kubernetes.io/hostname: monitortown
  tolerations:
  - key: "purpose"
    operator: "Equal"
    value: "monitoring"
    effect: "NoSchedule"

