# Based on https://github.com/vmwarecloudadvocacy/acme_fitness_demo
- name: Deploy sample Acme App
  hosts: portOfNeverland
  gather_facts: false
  become: true
  become_user: fisherman
  vars_files:
  - ./terraform_variables/tf_island-of-intelligence_vars_file.yml
  - ./terraform_variables/tf_network_vars_file.yml
  - ./terraform_variables/tf_k8node_vars_file.yml

  tasks:
  - name: Wait 300 seconds for ssh timeout, but only start checking after 1 seconds
    ansible.builtin.wait_for_connection:
      delay: 1
      timeout: 300

  - name: Copy sample app  yamls dir to remote
    ansible.builtin.copy:
      src: ../k8s/sampleAcmeApp
      dest: /tmp
      mode: 0700

  - name: Apply new k8s resources
    ansible.builtin.command: kubectl -n sampleapp apply -f /tmp/sampleAcmeApp/ --force --grace-period=0

  - name: Delete sample app yamls dir from remote
    ansible.builtin.file:
      path: /tmp/sampleAcmeApp/
      state: absent
