# Based on https://github.com/vmwarecloudadvocacy/acme_fitness_demo
- name: Deploy sample Acme App
  hosts: portOfNeverland
  gather_facts: false
  become: true
  become_user: fisherman
  vars_files:
  - ./terraform_variables/tf_island-of-intelligence_vars_file.yml
  - ./terraform_variables/tf_network_vars_file.yml
  - ./terraform_variables/tf_k8node_vars_file.yml

  tasks:
  - name: Wait 300 seconds for ssh timeout, but only start checking after 1 seconds
    ansible.builtin.wait_for_connection:
      delay: 1
      timeout: 300

  - name: Create sampleapp namespace
    ansible.builtin.command: kubectl create namespace sampleapp

  - name: Label sampleapp namespace for istio side-car injection
    ansible.builtin.command: kubectl label namespace sampleapp istio-injection=enabled

  - name: Create secrets
    ansible.builtin.shell:
      cmd: |
            kubectl -n sampleapp create secret generic cart-redis-pass --from-literal=password=pass
            kubectl -n sampleapp create secret generic catalog-mongo-pass --from-literal=password=pass
            kubectl -n sampleapp create secret generic order-postgres-pass --from-literal=password=pass
            kubectl -n sampleapp create secret generic users-mongo-pass --from-literal=password=pass
            kubectl -n sampleapp create secret generic users-redis-pass --from-literal=password=pass

  - name: Copy sample app  yamls dir to remote
    ansible.builtin.copy:
      src: ../k8s/sampleAcmeApp
      dest: /tmp
      mode: 0700

  - name: Apply new k8s resources
    ansible.builtin.command: kubectl -n sampleapp apply -f /tmp/sampleAcmeApp/

  - name: Delete sample app yamls dir from remote
    ansible.builtin.file:
      path: /tmp/sampleAcmeApp/
      state: absent

  - name: Create hpa
    ansible.builtin.shell:
      cmd: |
            kubectl -n sampleapp autoscale deployment cart --max=20 --min=1 --cpu-percent=80
            kubectl -n sampleapp autoscale deployment cart-redis --max=20 --min=1 --cpu-percent=80
            kubectl -n sampleapp autoscale deployment catalog --max=20 --min=1 --cpu-percent=80
            kubectl -n sampleapp autoscale deployment catalog-mongo --max=20 --min=1 --cpu-percent=80
            kubectl -n sampleapp autoscale deployment frontend --max=20 --min=1 --cpu-percent=80
            kubectl -n sampleapp autoscale deployment order --max=20 --min=1 --cpu-percent=80
            kubectl -n sampleapp autoscale deployment order-postgres --max=20 --min=1 --cpu-percent=80
            kubectl -n sampleapp autoscale deployment payment --max=20 --min=1 --cpu-percent=80
            kubectl -n sampleapp autoscale deployment pos --max=20 --min=1 --cpu-percent=80
            kubectl -n sampleapp autoscale deployment users --max=20 --min=1 --cpu-percent=80
            kubectl -n sampleapp autoscale deployment users-mongo --max=20 --min=1 --cpu-percent=80
            kubectl -n sampleapp autoscale deployment users-redis --max=20 --min=1 --cpu-percent=80

  - name: Deploy sampleapp virtual service
    ansible.builtin.shell:
      cmd: |
           cat <<EOF | kubectl apply -f -
                      apiVersion: networking.istio.io/v1alpha3
                      kind: VirtualService
                      metadata:
                        name: sampleappvirtualservice
                      spec:
                        hosts:
                        - neverland.com
                        gateways:
                        - neverlandgateway
                        http:
                        - match:
                          - uri:
                              prefix: /
                          name: sampleapp
                          rewrite:
                            uri: /
                          route:
                          - destination:
                              host: frontend.sampleapp.svc.cluster.local
                              port:
                                number: 80
                 EOF
