- name: worktown initialization  
  hosts: Worktowns
  gather_facts: no
  become: yes
  become_method: sudo
  become_user: root
  vars:
    username: kubeman

 
  tasks:
  - name: Wait 300 seconds for ssh timeout, but only start checking after 10 seconds
    wait_for_connection:
      delay: 10
      timeout: 300

  - name: include CreateUbuntuUser role
    include_role:
      name: CreateUbuntuUser
    vars:
      user_name: "{{ username }}"

  - name: install containerd and K8s with kubeadm
    include_role:
      name: InstallK8s
    vars:
      install_kubelet: true
      install_kubeadm: true
      install_kubectl: false
      K8s_version: 1.23.3-00
      nodeType: "worker"
      pod_network_cidr: 192.168.100.0/24

  - name: Execute command ‘date’
    command: "date"
    register: date_out
  - debug:
      var: date_out
