- name: worktown initialization  
  hosts: Worktowns
  gather_facts: no
  become: yes
  become_method: sudo
  become_user: root
  vars_files:
  - ./terraform_variables/tf_island-of-intelligence_vars_file.yml
  - ./terraform_variables/tf_network_vars_file.yml
  - ./variables.yaml

  tasks:
  - name: Wait 300 seconds for ssh timeout, but only start checking after 1 seconds
    wait_for_connection:
      delay: 1
      timeout: 300

  - name: install containerd and K8s with kubeadm
    include_role:
      name: InstallK8s
    vars:
      install_kubelet: true
      install_kubeadm: true
      install_kubectl: false
      nodeType: "worker"
