- name: worktown initialization  
  hosts: Worktowns
  gather_facts: no
  become: yes
  become_method: sudo
  become_user: root
  vars_files:
  - ./terraform_variables/tf_island-of-intelligence_vars_file.yml
  - ./terraform_variables/tf_network_vars_file.yml
  - ./variables.yaml

  tasks:
  - name: Wait 300 seconds for ssh timeout, but only start checking after 10 seconds
    wait_for_connection:
      delay: 10
      timeout: 300

  - name: Proxy settings for APT - 1
    file:
      path: "/etc/apt/apt.conf.d/proxy.conf"
      state: "touch"
      mode: u=rw,g=r,o=r

  - name: Proxy settings for APT - 2
    blockinfile:
      path: "/etc/apt/apt.conf.d/proxy.conf"
      block: |
             Acquire {
                      HTTP::proxy {{ ioi_internal_ip }}:{{ tinyproxy_port}};
                      HTTPS::proxy {{ ioi_internal_ip }}:{{ tinyproxy_port}};
                     }

  - name: install containerd and K8s with kubeadm
    include_role:
      name: InstallK8s
    vars:
      install_kubelet: true
      install_kubeadm: true
      install_kubectl: false
      K8s_version: {{ K8s_version }}
      nodeType: "worker"
      pod_network_cidr: {{ vpc_cidr }}
